apiVersion: v1
kind: Service
metadata:
  name: microservice-service
spec:
  ports:
    - name: microservice
      port: 5000
      targetPort: 5000
    - name: jupyter
      port: 8888
      targetPort: 8888
    - name: spark
      port: 8889
      targetPort: 8889
    - name: sonarqube
      port: 9000
      targetPort: 9000
  selector:
    app: microservice-app
  type: LoadBalancer